### ISSUE TITLE
Using animated hud causes severe lag (especially for Pyro after Jungle Inferno).

### ISSUE THREAD

**Issue by Chdata** [omnibombulator/Easy-TF2-Crosshairs#1]
It seems that calling all those hud animations on DamagePlayer causes severe lag, especially for multi-hit classes like pyro.

My game would essentially freeze whenever I damage someone, until I die or stop hitting them.

To fix this, I removed 'hudanimations_manifest.txt' and the other crosshair animation related stuff from or within other files.

This keeps the basic hud crosshair intact. Haven't tested if stripping it to the bare minimum needed for animating the crosshair on damage reduces or prevents the lag, since I don't really use that feature anyway.

**Comment by omnibombulator** [comment]
Resolved with the latest push
